# Generated by Django 4.0.6 on 2022-07-13 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videometa',
            options={'default_permissions': ('view',), 'get_latest_by': 'publishedAt', 'ordering': ['-publishedAt'], 'verbose_name': 'Video Metadata', 'verbose_name_plural': 'Videos Metadata'},
        ),
    ]
